version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building the React app..."
      - npm run build
      - echo "Building the Docker image..."
      - docker build -t my-react-app .
      - echo "Logging in to Docker Hub..."
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - echo "Tagging the Docker image..."
      - docker tag my-react-app:latest $DOCKER_USERNAME/my-react-app:latest
      - echo "Pushing the Docker image to Docker Hub..."
      - docker push $DOCKER_USERNAME/my-react-app:latest

artifacts:
  files:
    - '**/*'        # Include all files in the build directory
  discard-paths: yes
